# PySNMP SMI module. Autogenerated from smidump -f python CTROL-MIB
# by libsmi2pysnmp-0.1.3 at Fri Aug 15 12:04:18 2014,
# Python version sys.version_info(major=2, minor=7, micro=3, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( Bits, Integer32, Integer32, MibIdentifier, NotificationType, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, enterprises, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "Integer32", "MibIdentifier", "NotificationType", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "enterprises")

# Objects

myCompany = MibIdentifier((1, 3, 6, 1, 4, 1, 42))
testCount = MibScalar((1, 3, 6, 1, 4, 1, 42, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: testCount.setDescription("A sample count of something.")
tipoDisp = MibScalar((1, 3, 6, 1, 4, 1, 42, 2), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: tipoDisp.setDescription("A description of something")
modeloDisp = MibScalar((1, 3, 6, 1, 4, 1, 42, 4), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: modeloDisp.setDescription("Descripcion del controlador")
segClave = MibScalar((1, 3, 6, 1, 4, 1, 42, 5), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: segClave.setDescription("Clave de seguridad para TXs.")
verSW = MibScalar((1, 3, 6, 1, 4, 1, 42, 6), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: verSW.setDescription("Version de software")

# Augmentions

# Notifications

testTrap = NotificationType((1, 3, 6, 1, 4, 1, 42, 3)).setObjects(*() )
if mibBuilder.loadTexts: testTrap.setDescription("Test notification")

# Exports

# Objects
mibBuilder.exportSymbols("CTROL-MIB", myCompany=myCompany, testCount=testCount, tipoDisp=tipoDisp, modeloDisp=modeloDisp, segClave=segClave, verSW=verSW)

# Notifications
mibBuilder.exportSymbols("CTROL-MIB", testTrap=testTrap)

